let electron = require("electron");
//#region electron/preload.ts
electron.contextBridge.exposeInMainWorld("electronAPI", {
	printReceipt: (data) => electron.ipcRenderer.invoke("print-receipt", data),
	getConfig: (key) => electron.ipcRenderer.invoke("get-config", key),
	setConfig: (key, value) => electron.ipcRenderer.invoke("set-config", key, value),
	deleteConfig: (key) => electron.ipcRenderer.invoke("delete-config", key),
	savePendingTransaction: (type, currencyCode, foreignAmount, hufAmount, roundedHufAmount, rate, handlingFee, discountPercent, customerIdentifier, customerName, customerDocumentNumber, customerAddress, denominations) => electron.ipcRenderer.invoke("save-pending-transaction", type, currencyCode, foreignAmount, hufAmount, roundedHufAmount, rate, handlingFee, discountPercent, customerIdentifier, customerName, customerDocumentNumber, customerAddress, denominations),
	savePendingConversion: (fromCurrencyId, fromCurrencyCode, toCurrencyId, toCurrencyCode, fromAmount, calculatedHufAmount, calculatedToAmount, conversionRate, handlingFee, customerId, customerName, customerDocumentNumber, note) => electron.ipcRenderer.invoke("save-pending-conversion", fromCurrencyId, fromCurrencyCode, toCurrencyId, toCurrencyCode, fromAmount, calculatedHufAmount, calculatedToAmount, conversionRate, handlingFee, customerId, customerName, customerDocumentNumber, note),
	savePendingBankTransaction: (transactionType, currencyCode, amount, exchangeRate, hufAmount, vaultTerritoryId, bankName, bankReference, note) => electron.ipcRenderer.invoke("save-pending-bank-transaction", transactionType, currencyCode, amount, exchangeRate, hufAmount, vaultTerritoryId, bankName, bankReference, note),
	savePendingStorno: (payload) => electron.ipcRenderer.invoke("save-pending-storno", payload),
	getPendingTransactions: () => electron.ipcRenderer.invoke("get-pending-transactions"),
	getPendingTransactionCount: () => electron.ipcRenderer.invoke("get-pending-transaction-count"),
	getPendingConversions: () => electron.ipcRenderer.invoke("get-pending-conversions"),
	getPendingBankTransactions: () => electron.ipcRenderer.invoke("get-pending-bank-transactions"),
	getPendingStornos: () => electron.ipcRenderer.invoke("get-pending-stornos"),
	syncOffline: () => electron.ipcRenderer.invoke("sync-offline"),
	getSyncStatus: () => electron.ipcRenderer.invoke("get-sync-status"),
	getAppVersion: () => electron.ipcRenderer.invoke("get-app-version"),
	restartApp: () => electron.ipcRenderer.invoke("restart-app"),
	getPrinters: () => electron.ipcRenderer.invoke("get-printers"),
	savePendingDistribution: (targetBranchCode, currencyCode, amount, denominations, note) => electron.ipcRenderer.invoke("save-pending-distribution", targetBranchCode, currencyCode, amount, denominations, note),
	savePendingTransfer: (targetBranchId, targetBranchCode, currencyId, currencyCode, amount, hufValue, transferType, denominations, note) => electron.ipcRenderer.invoke("save-pending-transfer", targetBranchId, targetBranchCode, currencyId, currencyCode, amount, hufValue, transferType, denominations, note),
	getPendingTransfers: () => electron.ipcRenderer.invoke("get-pending-transfers"),
	savePendingCollection: (sourceBranchCode, currencyCode, amount, note) => electron.ipcRenderer.invoke("save-pending-collection", sourceBranchCode, currencyCode, amount, note),
	savePendingHandoverOperation: (payload) => electron.ipcRenderer.invoke("save-pending-handover-operation", payload),
	getPendingHandoverOperations: () => electron.ipcRenderer.invoke("get-pending-handover-operations"),
	getCachedBranchStatuses: () => electron.ipcRenderer.invoke("get-cached-branch-statuses"),
	getCachedBranchStatusTimestamp: () => electron.ipcRenderer.invoke("get-cached-branch-status-timestamp"),
	getCachedRates: () => electron.ipcRenderer.invoke("get-cached-rates"),
	getCachedCashDesks: () => electron.ipcRenderer.invoke("get-cached-cash-desks"),
	getCachedCashDeskTimestamp: () => electron.ipcRenderer.invoke("get-cached-cash-desk-timestamp"),
	getCachedWorkers: () => electron.ipcRenderer.invoke("get-cached-workers"),
	getCachedWorkerTimestamp: () => electron.ipcRenderer.invoke("get-cached-worker-timestamp"),
	saveLocalAuditEvent: (payload) => electron.ipcRenderer.invoke("save-local-audit-event", payload),
	getLocalAuditEvents: (limit) => electron.ipcRenderer.invoke("get-local-audit-events", limit),
	cameraSaveRecording: (transactionId, buffer, ext) => electron.ipcRenderer.invoke("camera-save-recording", transactionId, buffer, ext),
	cameraExportToUsb: (dateFrom, dateTo) => electron.ipcRenderer.invoke("camera-export-to-usb", dateFrom, dateTo),
	cameraListRecordings: (transactionId) => electron.ipcRenderer.invoke("camera-list-recordings", transactionId),
	cameraLocalStorageStats: () => electron.ipcRenderer.invoke("camera-local-storage-stats"),
	cameraLocalRecordingsByDate: (dateFrom, dateTo) => electron.ipcRenderer.invoke("camera-local-recordings-by-date", dateFrom, dateTo),
	cameraLocalReadFile: (filePath) => electron.ipcRenderer.invoke("camera-local-read-file", filePath),
	cameraLocalCleanup: (retentionDays) => electron.ipcRenderer.invoke("camera-local-cleanup", retentionDays),
	scanSaveDocument: (transactionId, documentType, imageBase64) => electron.ipcRenderer.invoke("scan-save-document", transactionId, documentType, imageBase64),
	scanGetDocument: (filepath) => electron.ipcRenderer.invoke("scan-get-document", filepath),
	scanListDocuments: (transactionId) => electron.ipcRenderer.invoke("scan-list-documents", transactionId),
	secureStoreToken: (token) => electron.ipcRenderer.invoke("secure-store-token", token),
	secureLoadToken: () => electron.ipcRenderer.invoke("secure-load-token"),
	secureClearToken: () => electron.ipcRenderer.invoke("secure-clear-token"),
	platform: process.platform
});
//#endregion
