-- Audit P0.5 (2026-05-03): perzisztens idempotency tabla.
--
-- A korabbi `IdempotencyGuard` (in-memory ConcurrentHashMap) hibai:
--   1. Multi-instance deploy eseten az egyik node nem latta a masik kulcsait
--      -> dupla pos terheles lehetseges.
--   2. Restart utan a teljes cache elveszett -> az ujraindulast koveto
--      automatic retry-ek dupla muveletet okozhattak.
--   3. A `cleanup()` `completedResults`-en mindig `false`-t adott vissza
--      (lasd a `removeIf` lambda) -> long-running monotonous memory leak.
--   4. NEM volt payload hash binding -> ugyanaz a key mas body-val a regi
--      eredmenyt kapta vissza (cache poisoning).
--   5. A nyers idempotency_key bekerult log-ba (audit trail leakage).
--
-- Megoldas: perzisztens tabla `(company_id, endpoint, idempotency_key)` UNIQUE
-- + `request_hash` payload binding + status (PROCESSING/COMPLETED/FAILED) +
-- response JSON + TTL `expires_at` (24h default).

CREATE TABLE IF NOT EXISTS idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    response_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT idempotency_status_check CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED'))
);

-- Egyedi kulcs multi-tenant + per-endpoint scope-pal.
-- Ha ket cég ugyanazt a key-t hasznalja, NEM utkozik (cross-tenant izolacio).
CREATE UNIQUE INDEX IF NOT EXISTS idempotency_record_unique_idx
    ON idempotency_record (company_id, endpoint, idempotency_key);

-- TTL cleanup job indexe (futasi gyakorisag: orankent).
CREATE INDEX IF NOT EXISTS idempotency_record_expires_idx
    ON idempotency_record (expires_at);
