-- ============================================================================
-- V256 (G19, EXCMD b9-munkavallalo): Munkavállaló al-nyilvántartások (1:N)
-- Üzemorvosi vizsgálat (FR-22), Szabadságok (FR-19), Gyerekek (FR-20).
-- Az employee törzshöz kapcsolódó al-táblák; a meglévő employee_address /
-- employee_bank_account mintáját követik.
-- ============================================================================

-- Üzemorvosi vizsgálat (FR-22): állapot / határidő / vizsgálat dátuma / eredmény / megkötés
CREATE TABLE IF NOT EXISTS employee_occupational_health (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT       NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    status          VARCHAR(50),                 -- pl. "Lezárt", "Folyamatban"
    deadline_date   DATE,                         -- határidő dátuma
    exam_date       DATE,                         -- vizsgálat dátuma
    result          VARCHAR(100),                 -- pl. "Alkalmas"
    restriction     VARCHAR(500),                 -- megkötés
    created_at      TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_emp_occ_health_employee ON employee_occupational_health(employee_id);

-- Szabadságok (FR-19): évenkénti soros nyilvántartás
CREATE TABLE IF NOT EXISTS employee_vacation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         BIGINT  NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    year                INTEGER NOT NULL,
    brought_forward     INTEGER NOT NULL DEFAULT 0,   -- áthozott
    vacation_days       INTEGER NOT NULL DEFAULT 0,   -- szabadság
    sick_leave_days     INTEGER NOT NULL DEFAULT 0,   -- betegszabadság
    taken_vacation      INTEGER NOT NULL DEFAULT 0,   -- kivett szabadság
    taken_sick_leave    INTEGER NOT NULL DEFAULT 0,   -- kivett betegszabadság
    sick_pay_days       INTEGER NOT NULL DEFAULT 0,   -- táppénz
    unpaid_leave_days   INTEGER NOT NULL DEFAULT 0,   -- fizetés nélküli szabadság
    created_at          TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_employee_vacation_year UNIQUE (employee_id, year)
);
CREATE INDEX IF NOT EXISTS idx_emp_vacation_employee ON employee_vacation(employee_id);

-- Gyerekek (FR-20)
CREATE TABLE IF NOT EXISTS employee_child (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT       NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    name            VARCHAR(200) NOT NULL,
    birth_date      DATE,
    created_at      TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_emp_child_employee ON employee_child(employee_id);
