-- V259: TEÁOR'08 tevékenységi kód referencia-tábla (legacy: TEAORTABLA / teaorvalasztas)
-- A G27 szabad-szöveges customer.teaor_code mezőjéhez kereshető törzs (typeahead picker).
-- Kurált, gyakori-kód halmaz (publikus TEÁOR'08 szabvány) — szabad szöveg továbbra is engedett.

CREATE TABLE IF NOT EXISTS teaor_code (
    id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code VARCHAR(8)   NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_teaor_code ON teaor_code (code);

INSERT INTO teaor_code (code, name) VALUES
  ('4711', 'Élelmiszer jellegű bolti vegyes kiskereskedelem'),
  ('4719', 'Iparcikk jellegű bolti vegyes kiskereskedelem'),
  ('4721', 'Zöldség, gyümölcs kiskereskedelme'),
  ('4730', 'Gépjárműüzemanyag-kiskereskedelem'),
  ('4754', 'Villamos háztartási készülék kiskereskedelme'),
  ('4771', 'Ruházat kiskereskedelme'),
  ('4776', 'Dísznövény, vetőmag, műtrágya, hobbiállat-eledel kiskereskedelme'),
  ('4778', 'Egyéb m.n.s. új áru kiskereskedelme'),
  ('4791', 'Csomagküldő, internetes kiskereskedelem'),
  ('4799', 'Egyéb nem bolti, piaci kiskereskedelem'),
  ('4520', 'Gépjárműjavítás, -karbantartás'),
  ('4531', 'Gépjárműalkatrész-nagykereskedelem'),
  ('4540', 'Motorkerékpár, -alkatrész kereskedelme, javítása'),
  ('4631', 'Zöldség-, gyümölcs-nagykereskedelem'),
  ('4690', 'Vegytermékkörű nagykereskedelem'),
  ('4941', 'Közúti áruszállítás'),
  ('4939', 'M.n.s. egyéb szárazföldi személyszállítás'),
  ('5210', 'Raktározás, tárolás'),
  ('5320', 'Egyéb postai, futárpostai tevékenység'),
  ('5510', 'Szállodai szolgáltatás'),
  ('5520', 'Üdülési, egyéb átmeneti szálláshely-szolgáltatás'),
  ('5610', 'Éttermi, mozgó vendéglátás'),
  ('5630', 'Italszolgáltatás'),
  ('5811', 'Könyvkiadás'),
  ('5814', 'Folyóirat, időszaki kiadvány kiadása'),
  ('6201', 'Számítógépes programozás'),
  ('6202', 'Információ-technológiai szaktanácsadás'),
  ('6209', 'Egyéb információ-technológiai szolgáltatás'),
  ('6311', 'Adatfeldolgozás, web-hoszting szolgáltatás'),
  ('6312', 'Világháló-portál szolgáltatás'),
  ('6411', 'Központi banki tevékenység'),
  ('6419', 'Egyéb monetáris közvetítés'),
  ('6430', 'Befektetési alapok, egyéb pénzügyi alap'),
  ('6491', 'Pénzügyi lízing'),
  ('6492', 'Egyéb hitelnyújtás'),
  ('6499', 'M.n.s. egyéb pénzügyi közvetítés'),
  ('6611', 'Pénz-, tőkepiac igazgatása'),
  ('6612', 'Értékpapír-, árutőzsdei ügynöki tevékenység'),
  ('6619', 'Egyéb pénzügyi kiegészítő tevékenység'),
  ('6622', 'Biztosítási ügynöki, brókeri tevékenység'),
  ('6630', 'Alapkezelés'),
  ('6810', 'Saját tulajdonú ingatlan adásvétele'),
  ('6820', 'Saját tulajdonú, bérelt ingatlan bérbeadása, üzemeltetése'),
  ('6831', 'Ingatlanügynöki tevékenység'),
  ('6920', 'Számviteli, könyvvizsgálói, adószakértői tevékenység'),
  ('7022', 'Üzletviteli, egyéb vezetési tanácsadás'),
  ('7111', 'Építészmérnöki tevékenység'),
  ('7311', 'Reklámügynöki tevékenység'),
  ('7410', 'Divat-, formatervezés'),
  ('7420', 'Fényképészet'),
  ('7430', 'Fordítás, tolmácsolás'),
  ('7711', 'Személygépjármű kölcsönzése'),
  ('7810', 'Munkaközvetítés'),
  ('7990', 'Egyéb foglalás'),
  ('8121', 'Általános épülettakarítás'),
  ('8211', 'Összetett adminisztratív szolgáltatás'),
  ('8559', 'M.n.s. egyéb oktatás'),
  ('8690', 'Egyéb humán-egészségügyi ellátás'),
  ('9602', 'Fodrászat, szépségápolás'),
  ('9609', 'M.n.s. egyéb személyi szolgáltatás'),
  ('4110', 'Épületépítési projekt szervezése'),
  ('4120', 'Lakó- és nem lakó épület építése'),
  ('4321', 'Villanyszerelés'),
  ('4322', 'Víz-, gáz-, fűtés-, légkondicionáló-szerelés'),
  ('4332', 'Épületasztalos-szerkezet szerelése')
ON CONFLICT (code) DO NOTHING;
