-- V278: F-001 fix — worker first-time setup token (publikus fiókátvétel ellen).
--
-- Probléma (audit F-001): a `/api/v1/auth/first-time-worker-setup` endpoint permitAll,
-- és ha egy worker `password_hash = NULL` (V196/V198/V230/V231 reset), a backend a
-- bootstrap-lezártságtól FÜGGETLENÜL, currentPassword NÉLKÜL állít új jelszót + ad JWT-t.
-- Mivel a worker-kódok (EBC + BORSI/BALI/KASZA…) a telepítő-wizardban publikusak, ez
-- hálózatról elérhető production endpointon (excvaluta.com) FIÓKÁTVÉTELT tesz lehetővé.
--
-- Fix: a bootstrap-lezárt utáni null-hash setuphoz admin által kiállított, egyszer
-- használatos, hash-elve (SHA-256) tárolt, lejáró setup-token KÖTELEZŐ. A raw token
-- csak egyszer, a kiállításkor kerül vissza az adminhoz; az adatbázis csak a hash-t tárolja
-- (a password_reset_token mintáját követve).
--
-- Átállás: a kezdeti (pre-bootstrap) telepítés érintetlen marad. A jelenleg null-hash
-- kollégák a meglévő flow-n befejezik a setupot a deploy előtt → utána kikerülnek a
-- null-hash állapotból. Minden ezutáni null-hash reset admin-tokent igényel.

CREATE TABLE IF NOT EXISTS worker_setup_token (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash      VARCHAR(64) NOT NULL,
    worker_id       BIGINT      NOT NULL,
    company_id      UUID        NOT NULL,
    created_by      BIGINT,                    -- a kiállító admin worker id-ja (audit)
    issued_at       TIMESTAMP   NOT NULL,
    expires_at      TIMESTAMP   NOT NULL,
    used_at         TIMESTAMP,
    CONSTRAINT uq_worker_setup_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_worker_setup_token_worker_active
    ON worker_setup_token (worker_id, used_at, expires_at);

COMMENT ON TABLE worker_setup_token IS
    'F-001: admin által kiállított, egyszer használatos, lejáró setup-token a null-hash '
    'first-time-worker-setup publikus fiókátvétel megakadályozására. Csak SHA-256 hash tárolt.';
