-- V35: Kerekítési szabályok tábla
-- Valutánként definiált kerekítési pontosság és irány-szabályok

CREATE TABLE IF NOT EXISTS rounding_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(3) NOT NULL UNIQUE,
    precision_value NUMERIC(10, 4) NOT NULL,
    small_threshold NUMERIC(15, 2) NOT NULL DEFAULT 100,
    large_threshold NUMERIC(15, 2) NOT NULL DEFAULT 10000,
    small_rounding VARCHAR(10) NOT NULL DEFAULT 'UP',
    large_rounding VARCHAR(10) NOT NULL DEFAULT 'DOWN'
);

CREATE INDEX IF NOT EXISTS idx_rounding_rule_currency ON rounding_rule(currency_code);

-- Seed data: Fő valuták kerekítési szabályai
INSERT INTO rounding_rule (currency_code, precision_value, small_threshold, large_threshold, small_rounding, large_rounding) VALUES
    ('EUR', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('USD', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('GBP', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('CHF', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('CZK', 0.1, 100, 10000, 'UP', 'DOWN'),
    ('PLN', 0.1, 100, 10000, 'UP', 'DOWN'),
    ('RON', 0.1, 100, 10000, 'UP', 'DOWN'),
    ('HRK', 0.1, 100, 10000, 'UP', 'DOWN'),
    ('DKK', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('SEK', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('NOK', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('HUF', 1, 1000, 100000, 'UP', 'DOWN'),
    ('CAD', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('AUD', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('JPY', 1, 1000, 100000, 'UP', 'DOWN'),
    ('BGN', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('RSD', 0.1, 100, 10000, 'UP', 'DOWN'),
    ('TRY', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('UAH', 0.01, 100, 10000, 'UP', 'DOWN'),
    ('CNY', 0.01, 100, 10000, 'UP', 'DOWN')
ON CONFLICT (currency_code) DO NOTHING;
