-- ============================================================================
-- V53: Employee HR törzsadat modul
-- Dolgozói személyi adatok, címek, bankszámlák, jogviszony, bér, kedvezmények
-- Az employee tábla KIEGÉSZÍTI a meglévő worker táblát (nem helyettesíti!)
-- ============================================================================

-- FEOR referencia tábla
CREATE TABLE IF NOT EXISTS feor_code (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10)  NOT NULL UNIQUE,
    title       VARCHAR(255) NOT NULL
);

-- Fő employee tábla — HR törzsadatok
CREATE TABLE IF NOT EXISTS employee (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Multi-tenant + kapcsolat a meglévő worker-hez
    company_id                      UUID         NOT NULL REFERENCES company(id),
    worker_id                       BIGINT                REFERENCES worker(id),

    -- Szervezeti egység (pl. "Szekszárd", "Pécs")
    organization_unit               VARCHAR(100),

    -- Sorszám az importból
    serial_number                   INTEGER,

    -- Személyi adatok
    last_name                       VARCHAR(100) NOT NULL,
    first_name                      VARCHAR(100) NOT NULL,
    birth_last_name                 VARCHAR(100),
    birth_first_name                VARCHAR(100),
    tax_id                          VARCHAR(20),
    social_security_number          VARCHAR(20),
    mothers_name                    VARCHAR(150),
    birth_date                      DATE,
    birth_country                   VARCHAR(100),
    birth_place                     VARCHAR(100),
    citizenship                     VARCHAR(100),

    -- Személyi igazolvány
    id_card_number                  VARCHAR(30),
    id_card_expiry                  DATE,

    -- Elérhetőség
    email                           VARCHAR(200),
    phone                           VARCHAR(30),

    -- Nyugdíj adatok
    pension_start_date              DATE,
    pension_type                    VARCHAR(50),

    -- Megváltozott munkaképesség
    reduced_work_capacity           BOOLEAN      DEFAULT FALSE,

    -- Jogviszony adatok
    employment_start_date           DATE,
    employment_type                 VARCHAR(200),
    employment_end_date             DATE,
    feor_code                       VARCHAR(10),
    job_title                       VARCHAR(200),
    work_hours_per_day              NUMERIC(4,2),
    has_secondary_education         BOOLEAN      DEFAULT FALSE,

    -- Bér adatok
    salary_type                     VARCHAR(5),     -- HB=havibér, OB=órabér
    salary_amount                   NUMERIC(12,2),
    payment_method                  VARCHAR(5),     -- B=banki, K=készpénz

    -- Végzettség / Szakképzés
    vocational_school_name          VARCHAR(300),
    vocational_qualification        VARCHAR(300),
    certificate_date                DATE,

    -- Megváltozott munkaképesség típusa
    reduced_work_capacity_type      VARCHAR(100),

    -- Adókedvezmények
    personal_tax_credit             VARCHAR(100),
    family_tax_credit               VARCHAR(100),
    two_children_credit             VARCHAR(100),
    four_plus_children_credit       VARCHAR(100),
    three_children_credit           VARCHAR(100),
    first_marriage_credit           VARCHAR(100),
    marriage_date                   DATE,
    credit_validity_last_month      VARCHAR(20),
    under_25_youth_credit_amount    VARCHAR(100),
    under_25_youth_credit_expiry    DATE,
    under_30_mother_credit_amount   VARCHAR(100),

    -- Aktív státusz (soft delete)
    active                          BOOLEAN      NOT NULL DEFAULT TRUE,

    -- Audit mezők
    created_at                      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMP,
    created_by                      VARCHAR(50),
    updated_by                      VARCHAR(50)
);

-- Címek tábla
CREATE TABLE IF NOT EXISTS employee_address (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT       NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    address_type      VARCHAR(20)  NOT NULL,  -- PERMANENT, MAILING, TEMPORARY
    postal_code       VARCHAR(10),
    city              VARCHAR(100),
    street_name       VARCHAR(200),
    street_type       VARCHAR(50),
    house_number      VARCHAR(20),
    building          VARCHAR(30),
    staircase         VARCHAR(30),
    floor             VARCHAR(20),
    door              VARCHAR(20)
);

-- Bankszámla tábla
CREATE TABLE IF NOT EXISTS employee_bank_account (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT       NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    account_type      VARCHAR(20)  NOT NULL,  -- SALARY, SZEP_CARD
    bank_code         VARCHAR(10),
    account_number    VARCHAR(50)
);

-- Indexek
CREATE INDEX IF NOT EXISTS idx_employee_company_id ON employee(company_id);
CREATE INDEX IF NOT EXISTS idx_employee_tax_id ON employee(tax_id);
CREATE INDEX IF NOT EXISTS idx_employee_social_security_number ON employee(social_security_number);
CREATE INDEX IF NOT EXISTS idx_employee_organization_unit ON employee(organization_unit);
CREATE INDEX IF NOT EXISTS idx_employee_worker_id ON employee(worker_id);
CREATE INDEX IF NOT EXISTS idx_employee_active ON employee(active);
CREATE INDEX IF NOT EXISTS idx_employee_address_employee_id ON employee_address(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_bank_account_employee_id ON employee_bank_account(employee_id);
