package hu.puzzleir.valuta.service;

import hu.puzzleir.valuta.entity.Branch;
import hu.puzzleir.valuta.entity.Company;
import hu.puzzleir.valuta.entity.RateWorkgroup;
import hu.puzzleir.valuta.exception.ValidationException;
import hu.puzzleir.valuta.repository.CompanyRepository;
import hu.puzzleir.valuta.repository.RateWorkgroupRepository;
import hu.puzzleir.valuta.security.SecurityUtils;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * FK-02: RateWorkgroupService — kód-egyediség cégen belül, tileColor frissítés, soft-delete.
 */
@ExtendWith(MockitoExtension.class)
class RateWorkgroupServiceTest {

    @Mock private RateWorkgroupRepository workgroupRepository;
    @Mock private CompanyRepository companyRepository;
    @InjectMocks private RateWorkgroupService service;

    private static final UUID COMPANY_ID = UUID.randomUUID();

    @Test
    @DisplayName("create: a kód-egyediséget CÉGEN BELÜL ellenőrzi (multi-tenant), nem globálisan")
    void create_checksCodeUniquenessWithinCompany() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            when(workgroupRepository.findByCompanyIdAndCode(COMPANY_ID, "WG01")).thenReturn(Optional.empty());
            when(companyRepository.findById(COMPANY_ID)).thenReturn(Optional.of(company));
            when(workgroupRepository.save(any(RateWorkgroup.class))).thenAnswer(inv -> inv.getArgument(0));

            RateWorkgroup wg = RateWorkgroup.builder().name("Pécs").code("WG01").tileColor("amber").build();
            RateWorkgroup saved = service.create(wg);

            assertThat(saved.getCompany()).isSameAs(company);
            assertThat(saved.getTileColor()).isEqualTo("amber");
            // A globális findByCode-ot NEM hívjuk (cross-tenant fals pozitív elkerülése).
            verify(workgroupRepository, never()).findByCode(anyString());
            verify(workgroupRepository).findByCompanyIdAndCode(COMPANY_ID, "WG01");
        }
    }

    @Test
    @DisplayName("create: ütköző kód CÉGEN BELÜL → ValidationException")
    void create_duplicateCodeWithinCompany_throws() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            when(workgroupRepository.findByCompanyIdAndCode(COMPANY_ID, "WG01"))
                    .thenReturn(Optional.of(new RateWorkgroup()));

            RateWorkgroup wg = RateWorkgroup.builder().name("Pécs").code("WG01").build();
            assertThatThrownBy(() -> service.create(wg))
                    .isInstanceOf(ValidationException.class)
                    .hasMessageContaining("WG01");
            verify(workgroupRepository, never()).save(any());
        }
    }

    @Test
    @DisplayName("update: a tileColor frissül")
    void update_persistsTileColor() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            UUID id = UUID.randomUUID();
            RateWorkgroup existing = RateWorkgroup.builder().id(id).name("Régi").code("WG01")
                    .company(company).active(true).tileColor(null).legacyGroupNumber(1).build();
            when(workgroupRepository.findById(id)).thenReturn(Optional.of(existing));
            when(workgroupRepository.save(any(RateWorkgroup.class))).thenAnswer(inv -> inv.getArgument(0));

            RateWorkgroup update = RateWorkgroup.builder().name("Új").active(true).tileColor("sky").legacyGroupNumber(7).build();
            RateWorkgroup result = service.update(id, update);

            assertThat(result.getName()).isEqualTo("Új");
            assertThat(result.getTileColor()).isEqualTo("sky");
            // A sorszám is frissül (P1: korábban némán elveszett).
            assertThat(result.getLegacyGroupNumber()).isEqualTo(7);
        }
    }

    @Test
    @DisplayName("FK02-D FR-17: create a kódot a sorszámból generálja (GROUP_NN), nem a klienstől")
    void create_codeAutoGeneratedFromSequence() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            when(workgroupRepository.findByCompanyIdAndLegacyGroupNumber(COMPANY_ID, 3)).thenReturn(Optional.empty());
            when(workgroupRepository.findByCompanyIdAndCode(COMPANY_ID, "GROUP_03")).thenReturn(Optional.empty());
            when(companyRepository.findById(COMPANY_ID)).thenReturn(Optional.of(company));
            when(workgroupRepository.save(any(RateWorkgroup.class))).thenAnswer(inv -> inv.getArgument(0));

            // A kliens "HACK" kódot küld — a szerver felülírja GROUP_03-ra a sorszámból.
            RateWorkgroup wg = RateWorkgroup.builder().name("Szeged").code("HACK").legacyGroupNumber(3).build();
            RateWorkgroup saved = service.create(wg);

            assertThat(saved.getCode()).isEqualTo("GROUP_03");
        }
    }

    @Test
    @DisplayName("FK02-D FR-17: a DEFAULT kód megmarad create-kor")
    void create_defaultCodePreserved() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            when(workgroupRepository.findByCompanyIdAndCode(COMPANY_ID, "DEFAULT")).thenReturn(Optional.empty());
            when(companyRepository.findById(COMPANY_ID)).thenReturn(Optional.of(company));
            when(workgroupRepository.save(any(RateWorkgroup.class))).thenAnswer(inv -> inv.getArgument(0));

            RateWorkgroup wg = RateWorkgroup.builder().name("Alap").code("DEFAULT").build();
            RateWorkgroup saved = service.create(wg);

            assertThat(saved.getCode()).isEqualTo("DEFAULT");
        }
    }

    @Test
    @DisplayName("FK02-E FR-1/FR-2: kód+sorszám nélkül a szerver a TELJES scope (aktív+inaktív) max+1-ét osztja ki")
    void create_autoAssignsSequenceOverActiveAndInactive() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            // 1,2 aktív + 5 INAKTÍV (soft-deleted) — a max+1 = 6 (nem 3), különben ütközne az
            // inaktív 5-ös foglalt sorszámával a V296 unique indexen (a felhasználó hibát látna).
            RateWorkgroup a = RateWorkgroup.builder().legacyGroupNumber(1).active(true).build();
            RateWorkgroup b = RateWorkgroup.builder().legacyGroupNumber(2).active(true).build();
            RateWorkgroup deleted = RateWorkgroup.builder().legacyGroupNumber(5).active(false).build();
            when(workgroupRepository.findByCompanyId(COMPANY_ID)).thenReturn(List.of(a, b, deleted));
            when(workgroupRepository.findByCompanyIdAndLegacyGroupNumber(COMPANY_ID, 6)).thenReturn(Optional.empty());
            when(workgroupRepository.findByCompanyIdAndCode(COMPANY_ID, "GROUP_06")).thenReturn(Optional.empty());
            when(companyRepository.findById(COMPANY_ID)).thenReturn(Optional.of(company));
            when(workgroupRepository.save(any(RateWorkgroup.class))).thenAnswer(inv -> inv.getArgument(0));

            // Az új frontend flow: se kód, se sorszám.
            RateWorkgroup wg = RateWorkgroup.builder().name("Új csoport").code("").build();
            RateWorkgroup saved = service.create(wg);

            assertThat(saved.getLegacyGroupNumber()).isEqualTo(6);
            assertThat(saved.getCode()).isEqualTo("GROUP_06");
        }
    }

    @Test
    @DisplayName("FK02-E: első csoport (üres scope) → sorszám 1")
    void create_autoAssignsFirstSequence() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            when(workgroupRepository.findByCompanyId(COMPANY_ID)).thenReturn(List.of());
            when(workgroupRepository.findByCompanyIdAndLegacyGroupNumber(COMPANY_ID, 1)).thenReturn(Optional.empty());
            when(workgroupRepository.findByCompanyIdAndCode(COMPANY_ID, "GROUP_01")).thenReturn(Optional.empty());
            when(companyRepository.findById(COMPANY_ID)).thenReturn(Optional.of(company));
            when(workgroupRepository.save(any(RateWorkgroup.class))).thenAnswer(inv -> inv.getArgument(0));

            RateWorkgroup saved = service.create(RateWorkgroup.builder().name("Első").code("").build());

            assertThat(saved.getLegacyGroupNumber()).isEqualTo(1);
            assertThat(saved.getCode()).isEqualTo("GROUP_01");
        }
    }

    @Test
    @DisplayName("FK02-D FR-15: create duplikált sorszám → ValidationException (VV-VALID-003)")
    void create_duplicateSequence_throws() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            when(workgroupRepository.findByCompanyIdAndLegacyGroupNumber(COMPANY_ID, 2))
                    .thenReturn(Optional.of(new RateWorkgroup()));

            RateWorkgroup wg = RateWorkgroup.builder().name("Győr").code("X").legacyGroupNumber(2).build();
            assertThatThrownBy(() -> service.create(wg))
                    .isInstanceOf(ValidationException.class)
                    .hasMessageContaining("VV-VALID-003");
            verify(workgroupRepository, never()).save(any());
        }
    }

    @Test
    @DisplayName("FK02-D FR-16: update másik csoport sorszámára → ValidationException (VV-VALID-003)")
    void update_duplicateSequence_throws() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            UUID id = UUID.randomUUID();
            UUID otherId = UUID.randomUUID();
            RateWorkgroup existing = RateWorkgroup.builder().id(id).name("A").code("GROUP_01")
                    .company(company).active(true).legacyGroupNumber(1).build();
            RateWorkgroup other = RateWorkgroup.builder().id(otherId).legacyGroupNumber(2).build();
            when(workgroupRepository.findById(id)).thenReturn(Optional.of(existing));
            when(workgroupRepository.findByCompanyIdAndLegacyGroupNumber(COMPANY_ID, 2))
                    .thenReturn(Optional.of(other));

            RateWorkgroup update = RateWorkgroup.builder().name("A").active(true).legacyGroupNumber(2).build();
            assertThatThrownBy(() -> service.update(id, update))
                    .isInstanceOf(ValidationException.class)
                    .hasMessageContaining("VV-VALID-003");
        }
    }

    @Test
    @DisplayName("FK02-D Codex P2: update regenerált kódja ütközik másik csoport kódjával → ValidationException")
    void update_regeneratedCodeCollides_throws() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            UUID id = UUID.randomUUID();
            UUID otherId = UUID.randomUUID();
            RateWorkgroup existing = RateWorkgroup.builder().id(id).name("A").code("GROUP_01")
                    .company(company).active(true).legacyGroupNumber(1).build();
            // A 9-es sorszám szabad, DE a "GROUP_09" kód már foglalt egy elcsúszott legacy csoporton.
            when(workgroupRepository.findById(id)).thenReturn(Optional.of(existing));
            when(workgroupRepository.findByCompanyIdAndLegacyGroupNumber(COMPANY_ID, 9)).thenReturn(Optional.empty());
            when(workgroupRepository.findByCompanyIdAndCode(COMPANY_ID, "GROUP_09"))
                    .thenReturn(Optional.of(RateWorkgroup.builder().id(otherId).build()));

            RateWorkgroup update = RateWorkgroup.builder().name("A").active(true).legacyGroupNumber(9).build();
            assertThatThrownBy(() -> service.update(id, update))
                    .isInstanceOf(ValidationException.class)
                    .hasMessageContaining("VV-VALID-003");
        }
    }

    @Test
    @DisplayName("FK02-D FR-16: update SAJÁT sorszámával (nem ütközik önmagával) → OK")
    void update_sameSequenceSelf_ok() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            UUID id = UUID.randomUUID();
            RateWorkgroup existing = RateWorkgroup.builder().id(id).name("A").code("GROUP_05")
                    .company(company).active(true).legacyGroupNumber(5).build();
            when(workgroupRepository.findById(id)).thenReturn(Optional.of(existing));
            // önmaga ugyanazzal a sorszámmal — a filter kizárja self-t, nincs hiba
            when(workgroupRepository.findByCompanyIdAndLegacyGroupNumber(COMPANY_ID, 5))
                    .thenReturn(Optional.of(existing));
            when(workgroupRepository.save(any(RateWorkgroup.class))).thenAnswer(inv -> inv.getArgument(0));

            RateWorkgroup update = RateWorkgroup.builder().name("A új").active(true).legacyGroupNumber(5).build();
            RateWorkgroup result = service.update(id, update);

            assertThat(result.getLegacyGroupNumber()).isEqualTo(5);
            assertThat(result.getCode()).isEqualTo("GROUP_05");
        }
    }

    @Test
    @DisplayName("softDelete: inaktivál (active=false) ÉS feloldja a branch-hozzárendelést, NEM töröl fizikailag")
    void softDelete_deactivatesAndClearsBranches() {
        try (MockedStatic<SecurityUtils> sec = mockStatic(SecurityUtils.class)) {
            sec.when(SecurityUtils::getCurrentCompanyId).thenReturn(COMPANY_ID);
            Company company = new Company();
            company.setId(COMPANY_ID);
            UUID id = UUID.randomUUID();
            Set<Branch> branches = new HashSet<>();
            branches.add(new Branch());
            RateWorkgroup existing = RateWorkgroup.builder().id(id).name("Törlendő").code("WG09")
                    .company(company).active(true).branches(branches).build();
            when(workgroupRepository.findById(id)).thenReturn(Optional.of(existing));
            when(workgroupRepository.save(any(RateWorkgroup.class))).thenAnswer(inv -> inv.getArgument(0));

            service.softDelete(id);

            assertThat(existing.getActive()).isFalse();
            assertThat(existing.getBranches()).isEmpty();
            verify(workgroupRepository, never()).delete(any());
            verify(workgroupRepository, never()).deleteById(any());
        }
    }
}
