object Form1: TForm1
  Left = 182
  Top = 111
  Width = 1276
  Height = 878
  Caption = 'Form1'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 40
    Top = 216
    Width = 745
    Height = 505
    TabOrder = 0
    object Panel2: TPanel
      Left = 16
      Top = 16
      Width = 41
      Height = 41
      Caption = '1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'MS Sans Serif'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
    end
    object Panel3: TPanel
      Left = 160
      Top = 16
      Width = 41
      Height = 41
      Caption = '4'
      TabOrder = 1
    end
    object Panel4: TPanel
      Left = 208
      Top = 16
      Width = 41
      Height = 41
      Caption = '5'
      TabOrder = 2
    end
    object Panel5: TPanel
      Left = 448
      Top = 16
      Width = 41
      Height = 41
      Caption = '10'
      TabOrder = 3
    end
    object Panel6: TPanel
      Left = 400
      Top = 64
      Width = 41
      Height = 41
      Caption = '24'
      TabOrder = 4
    end
    object Panel7: TPanel
      Left = 256
      Top = 16
      Width = 41
      Height = 41
      Caption = '6'
      TabOrder = 5
    end
    object Panel8: TPanel
      Left = 64
      Top = 16
      Width = 41
      Height = 41
      Caption = '2'
      TabOrder = 6
    end
    object Panel9: TPanel
      Left = 208
      Top = 64
      Width = 41
      Height = 41
      Caption = '20'
      TabOrder = 7
    end
    object Panel10: TPanel
      Left = 160
      Top = 160
      Width = 41
      Height = 41
      Caption = '49'
      TabOrder = 8
    end
    object Panel11: TPanel
      Left = 304
      Top = 64
      Width = 41
      Height = 41
      Caption = '22'
      TabOrder = 9
    end
    object Panel12: TPanel
      Left = 256
      Top = 64
      Width = 41
      Height = 41
      Caption = '21'
      TabOrder = 10
    end
    object Panel13: TPanel
      Left = 496
      Top = 64
      Width = 41
      Height = 41
      Caption = '26'
      TabOrder = 11
    end
    object Panel14: TPanel
      Left = 592
      Top = 16
      Width = 41
      Height = 41
      Caption = '13'
      TabOrder = 12
    end
    object Panel15: TPanel
      Left = 544
      Top = 16
      Width = 41
      Height = 41
      Caption = '12'
      TabOrder = 13
    end
    object Panel16: TPanel
      Left = 352
      Top = 16
      Width = 41
      Height = 41
      Caption = '8'
      TabOrder = 14
    end
    object Panel17: TPanel
      Left = 400
      Top = 16
      Width = 41
      Height = 41
      Caption = '9'
      TabOrder = 15
    end
    object Panel18: TPanel
      Left = 208
      Top = 112
      Width = 41
      Height = 41
      Caption = '35'
      TabOrder = 16
    end
    object Panel19: TPanel
      Left = 544
      Top = 64
      Width = 41
      Height = 41
      Caption = '27'
      TabOrder = 17
    end
    object Panel20: TPanel
      Left = 688
      Top = 16
      Width = 41
      Height = 41
      Caption = '15'
      TabOrder = 18
    end
    object Panel21: TPanel
      Left = 688
      Top = 64
      Width = 41
      Height = 41
      Caption = '30'
      TabOrder = 19
    end
    object Panel22: TPanel
      Left = 640
      Top = 112
      Width = 41
      Height = 41
      Caption = '44'
      TabOrder = 20
    end
    object Panel23: TPanel
      Left = 352
      Top = 112
      Width = 41
      Height = 41
      Caption = '38'
      TabOrder = 21
    end
    object Panel24: TPanel
      Left = 592
      Top = 112
      Width = 41
      Height = 41
      Caption = '43'
      TabOrder = 22
    end
    object Panel25: TPanel
      Left = 496
      Top = 112
      Width = 41
      Height = 41
      Caption = '41'
      TabOrder = 23
    end
    object Panel26: TPanel
      Left = 400
      Top = 160
      Width = 41
      Height = 41
      Caption = '54'
      TabOrder = 24
    end
    object Panel27: TPanel
      Left = 400
      Top = 112
      Width = 41
      Height = 41
      Caption = '39'
      TabOrder = 25
    end
    object Panel28: TPanel
      Left = 304
      Top = 352
      Width = 41
      Height = 41
      Caption = '112'
      TabOrder = 26
    end
    object Panel29: TPanel
      Left = 448
      Top = 112
      Width = 41
      Height = 41
      Caption = '40'
      TabOrder = 27
    end
    object Panel30: TPanel
      Left = 304
      Top = 208
      Width = 41
      Height = 41
      Caption = '67'
      TabOrder = 28
    end
    object Panel31: TPanel
      Left = 256
      Top = 160
      Width = 41
      Height = 41
      Caption = '51'
      TabOrder = 29
    end
    object Panel32: TPanel
      Left = 256
      Top = 304
      Width = 41
      Height = 41
      Caption = '96'
      TabOrder = 30
    end
    object Panel33: TPanel
      Left = 256
      Top = 352
      Width = 41
      Height = 41
      Caption = '111'
      TabOrder = 31
    end
    object Panel34: TPanel
      Left = 208
      Top = 256
      Width = 41
      Height = 41
      Caption = '80'
      TabOrder = 32
    end
    object Panel35: TPanel
      Left = 160
      Top = 256
      Width = 41
      Height = 41
      Caption = '79'
      TabOrder = 33
    end
    object Panel36: TPanel
      Left = 160
      Top = 304
      Width = 41
      Height = 41
      Caption = '94'
      TabOrder = 34
    end
    object Panel37: TPanel
      Left = 160
      Top = 448
      Width = 41
      Height = 41
      Caption = '139'
      TabOrder = 35
    end
    object Panel38: TPanel
      Left = 160
      Top = 352
      Width = 41
      Height = 41
      Caption = '109'
      TabOrder = 36
    end
    object Panel39: TPanel
      Left = 112
      Top = 160
      Width = 41
      Height = 41
      Caption = '48'
      TabOrder = 37
    end
    object Panel40: TPanel
      Left = 112
      Top = 112
      Width = 41
      Height = 41
      Caption = '33'
      TabOrder = 38
    end
    object Panel41: TPanel
      Left = 64
      Top = 160
      Width = 41
      Height = 41
      Caption = '47'
      TabOrder = 39
    end
    object Panel42: TPanel
      Left = 64
      Top = 256
      Width = 41
      Height = 41
      Caption = '77'
      TabOrder = 40
    end
    object Panel43: TPanel
      Left = 160
      Top = 400
      Width = 41
      Height = 41
      Caption = '124'
      TabOrder = 41
    end
    object Panel44: TPanel
      Left = 112
      Top = 400
      Width = 41
      Height = 41
      Caption = '123'
      TabOrder = 42
    end
    object Panel45: TPanel
      Left = 112
      Top = 304
      Width = 41
      Height = 41
      Caption = '93'
      TabOrder = 43
    end
    object Panel46: TPanel
      Left = 64
      Top = 304
      Width = 41
      Height = 41
      Caption = '92'
      TabOrder = 44
    end
    object Panel47: TPanel
      Left = 64
      Top = 448
      Width = 41
      Height = 41
      Caption = '137'
      TabOrder = 45
    end
    object Panel48: TPanel
      Left = 208
      Top = 208
      Width = 41
      Height = 41
      Caption = '65'
      TabOrder = 46
    end
    object Panel49: TPanel
      Left = 304
      Top = 448
      Width = 41
      Height = 41
      Caption = '142'
      TabOrder = 47
    end
    object Panel50: TPanel
      Left = 688
      Top = 304
      Width = 41
      Height = 41
      Caption = '105'
      TabOrder = 48
    end
    object Panel51: TPanel
      Left = 688
      Top = 256
      Width = 41
      Height = 41
      Caption = '90'
      TabOrder = 49
    end
    object Panel52: TPanel
      Left = 688
      Top = 352
      Width = 41
      Height = 41
      Caption = '120'
      TabOrder = 50
    end
    object Panel53: TPanel
      Left = 688
      Top = 208
      Width = 41
      Height = 41
      Caption = '75'
      TabOrder = 51
    end
    object Panel54: TPanel
      Left = 448
      Top = 160
      Width = 41
      Height = 41
      Caption = '55'
      TabOrder = 52
    end
    object Panel55: TPanel
      Left = 688
      Top = 160
      Width = 41
      Height = 41
      Caption = '60'
      TabOrder = 53
    end
    object Panel56: TPanel
      Left = 496
      Top = 160
      Width = 41
      Height = 41
      Caption = '56'
      TabOrder = 54
    end
    object Panel57: TPanel
      Left = 352
      Top = 448
      Width = 41
      Height = 41
      Caption = '143'
      TabOrder = 55
    end
    object Panel58: TPanel
      Left = 400
      Top = 448
      Width = 41
      Height = 41
      Caption = '144'
      TabOrder = 56
    end
    object Panel59: TPanel
      Left = 304
      Top = 304
      Width = 41
      Height = 41
      Caption = '97'
      TabOrder = 57
    end
    object Panel60: TPanel
      Left = 208
      Top = 160
      Width = 41
      Height = 41
      Caption = '50'
      TabOrder = 58
    end
    object Panel61: TPanel
      Left = 208
      Top = 448
      Width = 41
      Height = 41
      Caption = '140'
      TabOrder = 59
    end
    object Panel62: TPanel
      Left = 256
      Top = 400
      Width = 41
      Height = 41
      Caption = '126'
      TabOrder = 60
    end
    object Panel63: TPanel
      Left = 256
      Top = 448
      Width = 41
      Height = 41
      Caption = '141'
      TabOrder = 61
    end
    object Panel64: TPanel
      Left = 592
      Top = 448
      Width = 41
      Height = 41
      Caption = '148'
      TabOrder = 62
    end
    object Panel65: TPanel
      Left = 208
      Top = 304
      Width = 41
      Height = 41
      Caption = '95'
      TabOrder = 63
    end
    object Panel66: TPanel
      Left = 208
      Top = 400
      Width = 41
      Height = 41
      Caption = '125'
      TabOrder = 64
    end
    object Panel67: TPanel
      Left = 16
      Top = 448
      Width = 41
      Height = 41
      Caption = '136'
      TabOrder = 65
    end
    object Panel68: TPanel
      Left = 64
      Top = 400
      Width = 41
      Height = 41
      Caption = '122'
      TabOrder = 66
    end
    object Panel69: TPanel
      Left = 64
      Top = 352
      Width = 41
      Height = 41
      Caption = '107'
      TabOrder = 67
    end
    object Panel70: TPanel
      Left = 352
      Top = 208
      Width = 41
      Height = 41
      Caption = '68'
      TabOrder = 68
    end
    object Panel71: TPanel
      Left = 400
      Top = 304
      Width = 41
      Height = 41
      Caption = '99'
      TabOrder = 69
    end
    object Panel72: TPanel
      Left = 352
      Top = 352
      Width = 41
      Height = 41
      Caption = '113'
      TabOrder = 70
    end
    object Panel73: TPanel
      Left = 400
      Top = 352
      Width = 41
      Height = 41
      Caption = '114'
      TabOrder = 71
    end
    object Panel74: TPanel
      Left = 448
      Top = 304
      Width = 41
      Height = 41
      Caption = '100'
      TabOrder = 72
    end
    object Panel75: TPanel
      Left = 304
      Top = 400
      Width = 41
      Height = 41
      Caption = '127'
      TabOrder = 73
    end
    object Panel76: TPanel
      Left = 208
      Top = 352
      Width = 41
      Height = 41
      Caption = '110'
      TabOrder = 74
    end
    object Panel77: TPanel
      Left = 112
      Top = 256
      Width = 41
      Height = 41
      Caption = '78'
      TabOrder = 75
    end
    object Panel78: TPanel
      Left = 160
      Top = 112
      Width = 41
      Height = 41
      Caption = '34'
      TabOrder = 76
    end
    object Panel79: TPanel
      Left = 64
      Top = 112
      Width = 41
      Height = 41
      Caption = '32'
      TabOrder = 77
    end
    object Panel80: TPanel
      Left = 64
      Top = 208
      Width = 41
      Height = 41
      Caption = '62'
      TabOrder = 78
    end
    object Panel81: TPanel
      Left = 112
      Top = 64
      Width = 41
      Height = 41
      Caption = '18'
      TabOrder = 79
    end
    object Panel82: TPanel
      Left = 160
      Top = 64
      Width = 41
      Height = 41
      Caption = '19'
      TabOrder = 80
    end
    object Panel83: TPanel
      Left = 16
      Top = 160
      Width = 41
      Height = 41
      Caption = '46'
      TabOrder = 81
    end
    object Panel84: TPanel
      Left = 16
      Top = 112
      Width = 41
      Height = 41
      Caption = '31'
      TabOrder = 82
    end
    object Panel85: TPanel
      Left = 640
      Top = 256
      Width = 41
      Height = 41
      Caption = '89'
      TabOrder = 83
    end
    object Panel86: TPanel
      Left = 496
      Top = 256
      Width = 41
      Height = 41
      Caption = '86'
      TabOrder = 84
    end
    object Panel87: TPanel
      Left = 496
      Top = 448
      Width = 41
      Height = 41
      Caption = '146'
      TabOrder = 85
    end
    object Panel88: TPanel
      Left = 544
      Top = 448
      Width = 41
      Height = 41
      Caption = '147'
      TabOrder = 86
    end
    object Panel89: TPanel
      Left = 688
      Top = 400
      Width = 41
      Height = 41
      Caption = '135'
      TabOrder = 87
    end
    object Panel91: TPanel
      Left = 448
      Top = 448
      Width = 41
      Height = 41
      Caption = '145'
      TabOrder = 88
    end
    object Panel92: TPanel
      Left = 496
      Top = 208
      Width = 41
      Height = 41
      Caption = '71'
      TabOrder = 89
    end
    object Panel93: TPanel
      Left = 544
      Top = 256
      Width = 41
      Height = 41
      Caption = '87'
      TabOrder = 90
    end
    object Panel94: TPanel
      Left = 592
      Top = 400
      Width = 41
      Height = 41
      Caption = '133'
      TabOrder = 91
    end
    object Panel95: TPanel
      Left = 592
      Top = 256
      Width = 41
      Height = 41
      Caption = '88'
      TabOrder = 92
    end
    object Panel96: TPanel
      Left = 496
      Top = 304
      Width = 41
      Height = 41
      Caption = '101'
      TabOrder = 93
    end
    object Panel97: TPanel
      Left = 496
      Top = 352
      Width = 41
      Height = 41
      Caption = '116'
      TabOrder = 94
    end
    object Panel98: TPanel
      Left = 496
      Top = 400
      Width = 41
      Height = 41
      Caption = '131'
      TabOrder = 95
    end
    object Panel99: TPanel
      Left = 640
      Top = 400
      Width = 41
      Height = 41
      Caption = '134'
      TabOrder = 96
    end
    object Panel100: TPanel
      Left = 640
      Top = 448
      Width = 41
      Height = 41
      Caption = '149'
      TabOrder = 97
    end
    object Panel101: TPanel
      Left = 400
      Top = 400
      Width = 41
      Height = 41
      Caption = '129'
      TabOrder = 98
    end
    object Panel102: TPanel
      Left = 352
      Top = 304
      Width = 41
      Height = 41
      Caption = '98'
      TabOrder = 99
    end
    object Panel103: TPanel
      Left = 448
      Top = 400
      Width = 41
      Height = 41
      Caption = '130'
      TabOrder = 100
    end
    object Panel104: TPanel
      Left = 352
      Top = 400
      Width = 41
      Height = 41
      Caption = '128'
      TabOrder = 101
    end
    object Panel105: TPanel
      Left = 640
      Top = 160
      Width = 41
      Height = 41
      Caption = '59'
      TabOrder = 102
    end
    object Panel106: TPanel
      Left = 352
      Top = 256
      Width = 41
      Height = 41
      Caption = '83'
      TabOrder = 103
    end
    object Panel107: TPanel
      Left = 400
      Top = 256
      Width = 41
      Height = 41
      Caption = '84'
      TabOrder = 104
    end
    object Panel108: TPanel
      Left = 640
      Top = 208
      Width = 41
      Height = 41
      Caption = '74'
      TabOrder = 105
    end
    object Panel109: TPanel
      Left = 448
      Top = 256
      Width = 41
      Height = 41
      Caption = '85'
      TabOrder = 106
    end
    object Panel110: TPanel
      Left = 448
      Top = 352
      Width = 41
      Height = 41
      Caption = '115'
      TabOrder = 107
    end
    object Panel111: TPanel
      Left = 448
      Top = 208
      Width = 41
      Height = 41
      Caption = '70'
      TabOrder = 108
    end
    object Panel112: TPanel
      Left = 400
      Top = 208
      Width = 41
      Height = 41
      Caption = '69'
      TabOrder = 109
    end
    object Panel113: TPanel
      Left = 544
      Top = 352
      Width = 41
      Height = 41
      Caption = '117'
      TabOrder = 110
    end
    object Panel114: TPanel
      Left = 112
      Top = 448
      Width = 41
      Height = 41
      Caption = '138'
      TabOrder = 111
    end
    object Panel115: TPanel
      Left = 592
      Top = 304
      Width = 41
      Height = 41
      Caption = '103'
      TabOrder = 112
    end
    object Panel116: TPanel
      Left = 640
      Top = 352
      Width = 41
      Height = 41
      Caption = '119'
      TabOrder = 113
    end
    object Panel117: TPanel
      Left = 544
      Top = 304
      Width = 41
      Height = 41
      Caption = '102'
      TabOrder = 114
    end
    object Panel118: TPanel
      Left = 544
      Top = 208
      Width = 41
      Height = 41
      Caption = '72'
      TabOrder = 115
    end
    object Panel119: TPanel
      Left = 592
      Top = 352
      Width = 41
      Height = 41
      Caption = '118'
      TabOrder = 116
    end
    object Panel120: TPanel
      Left = 544
      Top = 400
      Width = 41
      Height = 41
      Caption = '132'
      TabOrder = 117
    end
    object Panel121: TPanel
      Left = 592
      Top = 208
      Width = 41
      Height = 41
      Caption = '73'
      TabOrder = 118
    end
    object Panel122: TPanel
      Left = 640
      Top = 304
      Width = 41
      Height = 41
      Caption = '104'
      TabOrder = 119
    end
    object Panel123: TPanel
      Left = 496
      Top = 16
      Width = 41
      Height = 41
      Caption = '11'
      TabOrder = 120
    end
    object Panel124: TPanel
      Left = 16
      Top = 64
      Width = 41
      Height = 41
      Caption = '16'
      TabOrder = 121
    end
    object Panel125: TPanel
      Left = 112
      Top = 352
      Width = 41
      Height = 41
      Caption = '108'
      TabOrder = 122
    end
    object Panel126: TPanel
      Left = 16
      Top = 208
      Width = 41
      Height = 41
      Caption = '61'
      TabOrder = 123
    end
    object Panel127: TPanel
      Left = 64
      Top = 64
      Width = 41
      Height = 41
      Caption = '17'
      TabOrder = 124
    end
    object Panel128: TPanel
      Left = 16
      Top = 256
      Width = 41
      Height = 41
      Caption = '76'
      TabOrder = 125
    end
    object Panel129: TPanel
      Left = 16
      Top = 352
      Width = 41
      Height = 41
      Caption = '106'
      TabOrder = 126
    end
    object Panel130: TPanel
      Left = 112
      Top = 208
      Width = 41
      Height = 41
      Caption = '63'
      TabOrder = 127
    end
    object Panel131: TPanel
      Left = 16
      Top = 400
      Width = 41
      Height = 41
      Caption = '121'
      TabOrder = 128
    end
    object Panel132: TPanel
      Left = 16
      Top = 304
      Width = 41
      Height = 41
      Caption = '91'
      TabOrder = 129
    end
    object Panel134: TPanel
      Left = 592
      Top = 160
      Width = 41
      Height = 41
      Caption = '58'
      TabOrder = 130
    end
    object Panel135: TPanel
      Left = 304
      Top = 160
      Width = 41
      Height = 41
      Caption = '52'
      TabOrder = 131
    end
    object Panel136: TPanel
      Left = 304
      Top = 112
      Width = 41
      Height = 41
      Caption = '37'
      TabOrder = 132
    end
    object Panel137: TPanel
      Left = 256
      Top = 208
      Width = 41
      Height = 41
      Caption = '66'
      TabOrder = 133
    end
    object Panel138: TPanel
      Left = 256
      Top = 256
      Width = 41
      Height = 41
      Caption = '81'
      TabOrder = 134
    end
    object Panel139: TPanel
      Left = 256
      Top = 112
      Width = 41
      Height = 41
      Caption = '36'
      TabOrder = 135
    end
    object Panel140: TPanel
      Left = 448
      Top = 64
      Width = 41
      Height = 41
      Caption = '25'
      TabOrder = 136
    end
    object Panel141: TPanel
      Left = 304
      Top = 16
      Width = 41
      Height = 41
      Caption = '7'
      TabOrder = 137
    end
    object Panel142: TPanel
      Left = 592
      Top = 64
      Width = 41
      Height = 41
      Caption = '28'
      TabOrder = 138
    end
    object Panel143: TPanel
      Left = 640
      Top = 64
      Width = 41
      Height = 41
      Caption = '29'
      TabOrder = 139
    end
    object Panel144: TPanel
      Left = 352
      Top = 160
      Width = 41
      Height = 41
      Caption = '53'
      TabOrder = 140
    end
    object Panel145: TPanel
      Left = 544
      Top = 160
      Width = 41
      Height = 41
      Caption = '57'
      TabOrder = 141
    end
    object Panel146: TPanel
      Left = 688
      Top = 112
      Width = 41
      Height = 41
      Caption = '45'
      TabOrder = 142
    end
    object Panel147: TPanel
      Left = 544
      Top = 112
      Width = 41
      Height = 41
      Caption = '42'
      TabOrder = 143
    end
    object Panel148: TPanel
      Left = 640
      Top = 16
      Width = 41
      Height = 41
      Caption = '14'
      TabOrder = 144
    end
    object Panel149: TPanel
      Left = 112
      Top = 16
      Width = 41
      Height = 41
      Caption = '3'
      TabOrder = 145
    end
    object Panel150: TPanel
      Left = 352
      Top = 64
      Width = 41
      Height = 41
      Caption = '23'
      TabOrder = 146
    end
    object Panel151: TPanel
      Left = 160
      Top = 208
      Width = 41
      Height = 41
      Caption = '64'
      TabOrder = 147
    end
    object Panel152: TPanel
      Left = 304
      Top = 256
      Width = 41
      Height = 41
      Caption = '82'
      TabOrder = 148
    end
  end
end
